"""Generated alias builder for runtime inventory snapshots."""

from __future__ import annotations

from collections import defaultdict

from app.config.models import GatewayConfig
from app.inventory.models import (
    DiscoveredModel,
    GeneratedAlias,
    GeneratedAliasCandidate,
    ModelClassification,
    ProviderSpecialRoute,
)

TEXT_CATEGORIES = ("free", "free-cheap", "fast", "general", "reasoning", "code")
MEDIA_MODALITIES = ("image", "video", "audio")
MEDIA_DEFAULT_CATEGORY = "default"
COMPAT_ALIAS_MAP = {
    "auto/free": "auto/text/free",
    "auto/free-cheap": "auto/text/free-cheap",
    "auto/fast": "auto/text/fast",
    "auto/general": "auto/text/general",
    "auto/reasoning": "auto/text/reasoning",
    "auto/code": "auto/text/code",
}


def build_generated_aliases(
    config: GatewayConfig,
    models: list[DiscoveredModel],
    classifications: list[ModelClassification],
    special_routes: list[ProviderSpecialRoute],
) -> list[GeneratedAlias]:
    model_map = {(item.provider, item.model_id): item for item in models}
    class_map = {(item.provider, item.model_id): item for item in classifications}
    special_by_provider = defaultdict(list)
    for route in special_routes:
        special_by_provider[route.provider].append(route)

    provider_aliases: list[GeneratedAlias] = []
    for provider_name, provider_cfg in sorted(config.providers.items(), key=lambda item: item[1].priority):
        if not provider_cfg.enabled:
            continue
        provider_models = [
            model
            for model in models
            if model.provider == provider_name and model.is_text_candidate and not model.excluded_reason
        ]
        for category in TEXT_CATEGORIES:
            candidates = _build_provider_candidates(
                provider=provider_name,
                category=category,
                models=provider_models,
                model_map=model_map,
                class_map=class_map,
                special_routes=special_by_provider.get(provider_name, []),
            )
            if not candidates:
                continue
            provider_aliases.append(
                GeneratedAlias(
                    alias_id=f"{provider_name}/text/{category}",
                    scope="provider",
                    modality="text",
                    category=category,
                    provider_scope=provider_name,
                    candidates=candidates,
                    generation_reason=f"generated from provider inventory for {provider_name}",
                )
            )
        for modality in MEDIA_MODALITIES:
            modality_models = [
                model
                for model in models
                if model.provider == provider_name and model.modality == modality and not model.is_special
            ]
            media_candidates = _build_media_candidates(modality_models)
            if not media_candidates:
                continue
            provider_aliases.append(
                GeneratedAlias(
                    alias_id=f"{provider_name}/{modality}/{MEDIA_DEFAULT_CATEGORY}",
                    scope="provider",
                    modality=modality,
                    category=MEDIA_DEFAULT_CATEGORY,
                    provider_scope=provider_name,
                    candidates=media_candidates,
                    generation_reason=f"generated from provider inventory for {provider_name} {modality}",
                )
            )

    alias_by_id = {item.alias_id: item for item in provider_aliases}
    global_aliases: list[GeneratedAlias] = []
    for category in TEXT_CATEGORIES:
        candidates: list[GeneratedAliasCandidate] = []
        for provider_name, provider_cfg in sorted(config.providers.items(), key=lambda item: item[1].priority):
            if not provider_cfg.enabled:
                continue
            provider_alias = alias_by_id.get(f"{provider_name}/text/{category}")
            if provider_alias is None:
                continue
            candidates.extend(provider_alias.candidates)
        if not candidates:
            continue
        global_aliases.append(
            GeneratedAlias(
                alias_id=f"auto/text/{category}",
                scope="global",
                modality="text",
                category=category,
                candidates=_dedupe_candidates(candidates),
                generation_reason="generated by merging provider-scoped aliases by provider priority",
            )
        )
    for modality in MEDIA_MODALITIES:
        candidates: list[GeneratedAliasCandidate] = []
        for provider_name, provider_cfg in sorted(config.providers.items(), key=lambda item: item[1].priority):
            if not provider_cfg.enabled:
                continue
            provider_alias = alias_by_id.get(f"{provider_name}/{modality}/{MEDIA_DEFAULT_CATEGORY}")
            if provider_alias is None:
                continue
            candidates.extend(provider_alias.candidates)
        if not candidates:
            continue
        global_aliases.append(
            GeneratedAlias(
                alias_id=f"auto/{modality}/{MEDIA_DEFAULT_CATEGORY}",
                scope="global",
                modality=modality,
                category=MEDIA_DEFAULT_CATEGORY,
                candidates=_dedupe_candidates(candidates),
                generation_reason=f"generated by merging provider-scoped {modality} aliases by provider priority",
            )
        )

    global_by_id = {item.alias_id: item for item in global_aliases}
    compat_aliases: list[GeneratedAlias] = []
    for compat_id, target_id in COMPAT_ALIAS_MAP.items():
        target = global_by_id.get(target_id)
        if target is None:
            continue
        compat_aliases.append(
            GeneratedAlias(
                alias_id=compat_id,
                scope="compat",
                modality="text",
                category=target.category,
                candidates=list(target.candidates),
                generation_reason=f"compatibility alias for {target_id}",
            )
        )

    return sorted(
        [*provider_aliases, *global_aliases, *compat_aliases],
        key=lambda item: (item.scope, item.alias_id),
    )


def _build_provider_candidates(
    *,
    provider: str,
    category: str,
    models: list[DiscoveredModel],
    model_map: dict[tuple[str, str], DiscoveredModel],
    class_map: dict[tuple[str, str], ModelClassification],
    special_routes: list[ProviderSpecialRoute],
) -> list[GeneratedAliasCandidate]:
    candidates: list[GeneratedAliasCandidate] = []
    if category in {"free", "free-cheap"}:
        for route in special_routes:
            if "free" in route.category_hints and route.modality == "text":
                candidates.append(
                    GeneratedAliasCandidate(
                        provider=provider,
                        model_id=route.route_id,
                        candidate_type="special_route",
                    )
                )

    ranked = sorted(
        models,
        key=lambda model: _category_sort_key(
            category,
            model_map[(model.provider, model.model_id)],
            class_map[(model.provider, model.model_id)],
        ),
        reverse=True,
    )
    if category == "free-cheap":
        free_models: list[GeneratedAliasCandidate] = []
        cheap_models: list[GeneratedAliasCandidate] = []
        for model in ranked:
            classification = class_map[(model.provider, model.model_id)]
            candidate = GeneratedAliasCandidate(
                provider=model.provider,
                model_id=model.model_id,
                candidate_type="model",
            )
            if classification.free_score > 0:
                free_models.append(candidate)
            elif classification.fast_score > 0:
                cheap_models.append(candidate)
        candidates.extend(free_models)
        candidates.extend(cheap_models)
        return _dedupe_candidates(candidates)

    for model in ranked:
        classification = class_map[(model.provider, model.model_id)]
        if not _model_matches_category(category, classification):
            continue
        candidates.append(
            GeneratedAliasCandidate(
                provider=model.provider,
                model_id=model.model_id,
                candidate_type="model",
            )
        )
    return _dedupe_candidates(candidates)


def _model_matches_category(category: str, classification: ModelClassification) -> bool:
    if category == "free":
        return classification.free_score > 0
    if category == "free-cheap":
        return classification.free_score > 0 or classification.fast_score > 0
    if category == "fast":
        return classification.fast_score > 0
    if category == "general":
        return classification.general_score > 0
    if category == "reasoning":
        return classification.reasoning_score > 0
    if category == "code":
        return classification.code_score > 0
    return False


def _category_sort_key(
    category: str,
    model: DiscoveredModel,
    classification: ModelClassification,
) -> tuple[int, int, int, int]:
    primary = {
        "free": classification.free_score,
        "free-cheap": max(classification.free_score, classification.fast_score),
        "fast": classification.fast_score,
        "general": classification.general_score,
        "reasoning": classification.reasoning_score,
        "code": classification.code_score,
    }.get(category, 0)
    secondary = classification.general_score
    tertiary = _capability_bonus(category, model, classification)
    quaternary = 1 if classification.tool_capable and not classification.tool_disabled else 0
    return primary, secondary, tertiary, quaternary


def _capability_bonus(category: str, model: DiscoveredModel, classification: ModelClassification) -> int:
    if category == "code":
        if model.tools_state == "supported":
            return 3
        if model.tools_state == "unknown":
            return 1
        return 0
    if category in {"free-cheap", "fast", "general", "reasoning"}:
        bonus = 0
        bonus += 1 if model.chat_state == "supported" else 0
        bonus += 1 if model.responses_state == "supported" else 0
        bonus += 1 if model.stream_state == "supported" else 0
        return bonus
    if category == "free":
        return 1 if model.chat_state == "supported" else 0
    return 0


def _dedupe_candidates(candidates: list[GeneratedAliasCandidate]) -> list[GeneratedAliasCandidate]:
    seen: set[tuple[str, str, str]] = set()
    result: list[GeneratedAliasCandidate] = []
    for item in candidates:
        marker = (item.provider, item.model_id, item.candidate_type)
        if marker in seen:
            continue
        seen.add(marker)
        result.append(item)
    return result


def _build_media_candidates(models: list[DiscoveredModel]) -> list[GeneratedAliasCandidate]:
    ranked = sorted(
        models,
        key=lambda model: (
            1 if model.is_free else 0,
            1 if not model.is_preview else 0,
            len(model.source_key_ids),
        ),
        reverse=True,
    )
    return _dedupe_candidates(
        [
            GeneratedAliasCandidate(
                provider=model.provider,
                model_id=model.model_id,
                candidate_type="model",
            )
            for model in ranked
        ]
    )
